name: woosignal_woocommerce_example
description: Demonstrates how to use the wp_json_api plugin.

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  wp_json_api:
    path: ../

flutter:

  uses-material-design: true
